name: Check Precompiled Binaries

on:
  pull_request:
    paths:
      - 'enc_bootloader/**'
      - 'picoboot_flash_id/**'
      - 'xip_ram_perms/**'

jobs:
  check-precompiled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: sudo apt install cmake ninja-build python3 build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib libusb-1.0-0-dev

      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: pico-sdk
          submodules: 'true'

      - name: Build and Install
        run: |
          cmake -S . -B build -G "Ninja" -D PICO_SDK_PATH="${{ github.workspace }}/pico-sdk" -D USE_PRECOMPILED=FALSE
          cmake --build build
          sudo cmake --install build

      - name: Check precompiled binaries have been updated
        run: |
          updated_files=$(curl -s -u "${{ github.repository_owner }}":"${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "${{ github.event.pull_request._links.self.href }}/files")
          updated_files=$(jq -r '.[] | .filename' <<<"$updated_files")

          echo "Updated files: $updated_files"

          # enc_bootloader
          echo "$updated_files" | grep -q "enc_bootloader/.*\.elf"
          enc_bootloader_elf_not_updated=$?
          if [ $enc_bootloader_elf_not_updated -eq 1 ]; then
              echo "Checking enc_bootloader files for modifications as ELFs have not been updated"
              for file in enc_bootloader/*; do
                  if echo "$file" | grep -q "CMakeLists.txt" || echo "$file" | grep -q "BUILD.bazel"; then
                      continue
                  fi
                  if echo "$updated_files" | grep -q "$file"; then
                      echo "File $file is in the PR but enc_bootloader ELFs have not been updated"
                      exit 1
                  fi
              done
          fi

          # picoboot_flash_id
          echo "$updated_files" | grep -q "picoboot_flash_id/.*\.bin"
          flash_id_bin_not_updated=$?
          if [ $flash_id_bin_not_updated -eq 1 ]; then
              echo "Checking picoboot_flash_id files for modifications as BINs have not been updated"
              for file in picoboot_flash_id/*; do
                  if echo "$file" | grep -q "CMakeLists.txt" || echo "$file" | grep -q "BUILD.bazel"; then
                      continue
                  fi
                  if echo "$updated_files" | grep -q "$file"; then
                      echo "File $file is in the PR but flash_id BINs have not been updated"
                      exit 1
                  fi
              done
          fi

          # xip_ram_perms
          echo "$updated_files" | grep -q "xip_ram_perms/.*\.elf"
          xip_ram_perms_elf_not_updated=$?
          if [ $xip_ram_perms_elf_not_updated -eq 1 ]; then
              echo "Checking xip_ram_perms files for modifications as ELFs have not been updated"
              for file in xip_ram_perms/*; do
                  if echo "$file" | grep -q "CMakeLists.txt" || echo "$file" | grep -q "BUILD.bazel"; then
                      continue
                  fi
                  if echo "$updated_files" | grep -q "$file"; then
                      echo "File $file is in the PR but xip_ram_perms ELFs have not been updated"
                      exit 1
                  fi
              done
          fi

      - name: Upload new precompiled binaries
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: precompiled-binaries
          path: |
            enc_bootloader/enc_bootloader.elf
            enc_bootloader/enc_bootloader_mbedtls.elf
            picoboot_flash_id/flash_id.bin
            xip_ram_perms/xip_ram_perms.elf
